export {default as  Header} from "./Header/Header"
export {default as  Category} from "./Category/Category"
export {default as  Footer} from "./Footer/Footer"
export {default as  Home} from "./Home/Home"
export {default as  SingleProduct} from "./SingleProduct/SingleProduct"
export {default as  Newsletter} from "./Footer/Newsletter/Newsletter"
export {default as Register}    from "./auth/Register"
export {default as Login}    from "./auth/Login"
